import {
  LayoutDashboard,
  Users,
  FolderKanban,
  CheckSquare,
  Layers,
  Calendar,
  FileText,
  Network,
  Database,
  FileCode,
  Plus,
  Search,
  FileCheck,
  AlertTriangle,
  Clock,
  CheckCircle,
  TrendingUp,
  BarChart3,
  ClipboardCheck,
  Bug,
  Receipt,
  Wrench,
  ArrowUpRight,
} from 'lucide-angular';

export const appIcons = {
  dashboard: LayoutDashboard,
  customers: Users,
  projects: FolderKanban,
  'approval-center': CheckSquare,
  layers: Layers,
  timeline: Calendar,
  requirements: FileText,
  dfd: Network,
  'er-diagram': Database,
  specifications: FileCode,
  plus: Plus,
  search: Search,
  'file-check': FileCheck,
  'alert-triangle': AlertTriangle,
  clock: Clock,
  'check-circle': CheckCircle,
  'trending-up': TrendingUp,
  'bar-chart-3': BarChart3,
  'clipboard-check': ClipboardCheck,
  bug: Bug,
  receipt: Receipt,
  wrench: Wrench,
  'arrow-up-right': ArrowUpRight,
  'folder-kanban': FolderKanban,
  users: Users,
};
