package com.softflow.enums;

public enum SdlcStatus {
    PROSPECT,
    CONTRACT_DRAFTING,
    CONTRACT_SIGNED,
    REQUIREMENT_GATHERING,
    REQUIREMENT_APPROVAL,
    SYSTEM_ANALYSIS,
    DFD_DESIGN,
    ER_DESIGN,
    SPECIFICATION_DESIGN,
    SPECIFICATION_APPROVAL,
    PLANNING,
    DEVELOPMENT,
    INTERNAL_TESTING,
    UAT,
    BUG_FIXING,
    READY_FOR_DELIVERY,
    DELIVERED,
    INVOICING,
    CLOSED,
    MA_ACTIVE
}
